#!/bin/sh

if [ -d env ]; then
    . env/bin/activate
fi

if which coverage >/dev/null 2>&1; then
    coverage run --include 'markovchain/*' setup.py test && coverage report -m
else
    ./setup.py test
fi
